name: incubapp_lite
description: A new Flutter project.

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^2.12.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.2.1
  android_flutter_wifi: ^0.1.2
  connectivity: ^3.0.6
  permission_handler: ^11.3.1
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  webview_flutter: ^4.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^3.0.2



  #mobile_app: any
flutter:

  assets:
    - assets/logo.png

  uses-material-design: true

