name: incubapp_lite
description: A new Flutter project.

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^2.12.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.1.0
  http: ^1.1.0
  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0
  android_flutter_wifi: ^0.1.2
  permission_handler: ^9.2.0
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.6
  webview_flutter: ^2.0.13
  flutter_inappwebview: ^5.3.2
  android_intent_plus: ^4.0.0
  meta: ^1.15.0
  shared_preferences: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter_launcher_icons:

  android: true
  image_path: "assets/icono.png"


flutter:

  assets:
    - assets/logo.png
    - assets/icono.png

  uses-material-design: true

